//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asp_UserSubscriptions
    {
        public int Rec_Id { get; set; }
        public Nullable<int> CompanySubcr_Id { get; set; }
        public string UserId { get; set; }
        public Nullable<System.Guid> Subscription_Id { get; set; }
        public string Full_Name { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<byte> Subsc_Status { get; set; }
    }
}
