//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersCompany
    {
        public int Id { get; set; }
        public string Customer_Code { get; set; }
        public string Commerical_Name { get; set; }
        public string Commerical_Name_En { get; set; }
        public string Company_Prefix { get; set; }
        public string Database_Name { get; set; }
        public string HostName { get; set; }
        public Nullable<int> Trial_Period { get; set; }
        public string Responsible_Name { get; set; }
        public string Responsible_Tel { get; set; }
        public string Responsible_Email { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Start_Date { get; set; }
        public string Renewal_Date { get; set; }
        public string End_Date { get; set; }
        public string LogoPath { get; set; }
    }
}
